# Load the image
wi = Image("tizen.png");

# Get screen dimensions
sw = Window.GetWidth();
sh = Window.GetHeight();

# Resize the image
ri = wi.Scale(sw, sh);

# Create a sprite for the image
ws = Sprite(ri);

ws.SetZ(-100);

# Get a sprite for text
ms = Sprite();
ms.SetPosition(sw * 0.5, sh * 0.7, 10000);

fun mc(text) {
	if (text == "Updating...") {
		ms.SetImage(Image.Text(text, 255, 255, 255));
	}
}

Plymouth.SetUpdateStatusFunction(mc);
